### ISSUE TITLE
Checklist: Observe attributes

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#12]
**UC Description:**
Attributes for LDAP entities might have text or binary format.
Text attributes shall be displayed as key-value pairs.
For Binary types, just HEX view is implemented for MVP release.

**Checklist:**
 - for each object in DIT all its attributes are displayed;
 - for each attribute the following properties are displayed: attribute name, value, type;
 - for attributes of type Binary values are displayed as HEX;
 - for attributes of types below values are correctly displayed:
   - Boolean;
   - Integer;
   - Distinguished Name;
   - Directory String;
   - Object Identifier;
   - Octet String;
   - Telephone Number;
   - Generalized Time;
 - for the attributes of types not listed above values are correctly displayed, if possible;
 - attributes which are of category Must-have and the attributes which are of category May-have in current scheme for the selected object are visually distinguished.

**Comment by d-markevich** [comment]
Согласен

**Comment by d-markevich** [comment]
Дмитрий, вы когда тест прогнали и вешайте issue на меня, я буду видеть что мне надо рассмотреть, не понравится - верну на вас

**Comment by dmitry-vrachev** [comment]
> отображается ли у нас сейчас рядом с атрибутом имя его класса

Покрыто #21
