### ISSUE TITLE
Checklist: Edit Single Entity

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#13]
**UC description:**
Attributes of single existing entity of DIT can be edited. Editing capabilities for the attributes' names and types are restricted by selected scheme, for the attributes' values - by attribute type.

**Checklist:**
- Attributes of category Must-have are placed in the upper part of attributes grid. They are distinguished by color from the attributes of category May-have. 
  - Neither new attributes of category Must-have can be added, nor existing attributes of this category can be deleted.
  - Only value can be edited for these attributes. 
- Attributes of category May-have are placed below the attributes of category Must-have. They are distinguished by color from the attributes of category Must-have. 
  - New attributes of category May-have can be added, existing attributes of this category can be deleted. 
  - Value and name can be changed for the attributes of this category. 
  - Name can be selected from the combo box in corresponding column. This combo box contains all available names for the attributes of category May-have. The names are read from the scheme. Already used names are not available in the selection list. Type of attribute is auto-selected after the name selection.
  - New attributes are highlighted with bold.
 - Values are edited in the same way for attributes of both categories. Value is edited directly in the attributes grid in the Value column. In-place validation is performed after the user presses Enter in the editable field or changes focus.
   - Values where validation failed are highlighted by red color.
   - Changed values are highlighted with bold.
   - Value validation is available for the attributes of types listed below:
     - Boolean;
     - Integer;
     - Distinguished Name;
     - Directory String;
     - Object Identifier;
     - Octet String;
     - Telephone Number;
     - Generalized Time;
- User can save changes by selecting corresponding option from application menu. In case there are any non-valid changes - user gets a message and the saving is not performed.
- In case user selects another object in DIT while having some unsaved changes - a message appears asking if these changes should be saved. In case user selects Yes and there are any non-valid changes - user gets a message, the saving is not performed, changing object in DIT tree is not performed.

**Comment by d-markevich** [comment]
@Shcherbich
@dmitry-vrachev 
@andrew-tyapukhin 

Я может чего-то не въехал, Егор меня поправит  

> Value and name can be changed for the attributes of this category

Имя атрибута нельзя поменять, оно задано в схеме, его можно только выбрать. Замена имени атрибута в строке означает создание нового. Т.е. давайте разделим кейсы - создать/редактировать/убрать. В создать "выпадает список" и он заполняет имя, а в редактировать уже только value. Хотите новый - надо этот "удалить" и новый создать.

Описанный кейс не имеет однозначного результата, потому как не понятно что надо было сделать, поведение описано как погода "штормит".

> New attributes

Новые атрибуты или новые значения? Скорее не new а unsaved, ну или тогда прийдется вводить и new и unsaved.

> Values are edited in the same way for attributes of both categories.

Кто у нас both? босс :-)

Мы вроде bin не собирались редактировать? Егор?

> Values where validation failed are highlighted by red color

Валидируем по вводу или при сохранении? Оно когда красным станет, сразу или после попытки сохранения? Определитесь с разработчиками с логикой. С точки зрения текущего концепта - лучше валидация по сохранению с выдачей обратно данных о том, что валидация не прошла и полей по которым не прошла.

> In case user selects another object in DIT while having some unsaved changes - a message appears asking if these changes should be saved. In case user selects Yes and there are any non-valid changes - user gets a message, the saving is not performed, changing object in DIT tree is not performed.

ой ничего не понял....

- Предусловие - текущий объект отредактирован но не сохранен
- Действие - пользователь кликает на другой объект в дереве
- Реакция - система выдает сообщение "текущий объект не сохранен, сохранить изменения? Да/Нет"
- Действие - Пользователь выбирает "Нет"
- Реакция - Система переходит на другой объект в дереве, изменения объекта не сохраняются
- Действие - Пользователь выбирает "Да"
- Реакция - система сохраняет объект и переходит на другой объект в дереве выбранный пользователем.
- Исключение: Если сохранение не удалось из-за нарушения правил валидация система возвращается в состояние редактирования объекта и выдает сообщение "Объект не может быть сохранен из за ошибки валидации. Продолжить редактирование или отменить изменения? Да/Нет" - далее смотрит кейс такой-то про сохранение объекта.

---

Советы:
- Пишите проще - действие - реакция, это не роман
- Действие имеет смысл в контексте, если контекст не ясен и действие не ясно. "Он взял с полки туалетную бумагу" что дальше? Пошел рассчитаться в кассу? Высморкался? или?
- Зачем такое большое issue? Мельче issue быстрее закроем

Вы же вроде под Agile косите :-)

**Comment by d-markevich** [comment]
Ой, совсем забыл...

Мы изменяем объект и атрибуты, интерфейс это классно, но нужно же проверить что они именно в этом виде попали в сам LDAP. Т.е. проверки должны в себя включать выгрузку в текстовик и проверку что именно тот атрибут добавился/удалился и его значение поменялось в соотвествии с кейсом.

Я уже слышу "мы же библиотеку используем", да, но один разок надо проверить и на старуху бывает проруха, далее см. классику

**Comment by dmitry-vrachev** [comment]
>Т.е. давайте разделим кейсы - создать/редактировать/убрать.

Ок, поменяем, непринципиально. Чеклист исправлю.

>Новые атрибуты или новые значения? 

Учитывая, что мы незаданные атрибуты категории May-have не показываем - новые атрибуты.

>Скорее не new а unsaved, ну или тогда прийдется вводить и new и unsaved.

Не вижу принципиальной разницы, в любом случае на сервере этих данных нет. New - в любом случае unsaved.

>Кто у нас both? босс :-)

Both у нас обе категории - Must-have и May-have. Попробую перефразировать, если так неясно.

>Мы вроде bin не собирались редактировать?

У нас записано, что собирались, но исключительно как hex.

>Валидируем по вводу или при сохранении? Оно когда красным станет, сразу или после попытки сохранения?

Там чуть выше пассажа про подкрашивание красным указано, что 

>In-place validation is performed after the user presses Enter in the editable field or changes focus.

т.е. валидируем сразу по вводу. 

>С точки зрения текущего концепта - лучше валидация по сохранению с выдачей обратно данных о том, что валидация не прошла и полей по которым не прошла.

Обсудим с разработчиками, текущая имплементация предполагала in-place валидацию.

>Предусловие...
Действие...
Реакция...

Вроде договаривались о том, что как раз такой формат с глубокой детализацией использовать не будем и будем писать высокоуровнево. Можно, конечно, и на детализированные тест-кейсы перейти, но это тогда будет вообще другой формат документа.

>Зачем такое большое issue? Мельче issue быстрее закроем
Вы же вроде под Agile

Мы рассматриваем этот кусок функционала как один юз-кейс, с точки зрения Agile это одна Story. Соответственно закрываем мы ее тоже одним куском, поэтому и чеклист такой. Согласитесь, не очень логично закрывать, например, редактирование без сохранения или сохранение без редактирования.

**Comment by dmitry-vrachev** [comment]
>проверки должны в себя включать ... проверку что именно тот атрибут добавился/удалился и его значение поменялось в соотвествии с кейсом.

Опять же это к вопросу о детализации, я не писал очевидные вещи. Т.е. имхо очевидно, что "сохранилось" - это "изменено на сервере", а не "кнопочка нажалась". Если надо писать - будем писать. 

>выгрузку в текстовик 
Принципиально это именно так делать? Я сейчас тупо в другом редакторе смотрю.

**Comment by d-markevich** [comment]
> > проверки должны в себя включать ... проверку что именно тот атрибут добавился/удалился и его значение поменялось в соотвествии с кейсом.
> 
> Опять же это к вопросу о детализации, я не писал очевидные вещи.

Это не "действие" это "результат", я готов пропускать промежуточные действия, но не результаты. Совершенно не очевидно, что оно сохранилось правильно.

> Т.е. имхо очевидно, что "сохранилось" - это "изменено на сервере", а не "кнопочка нажалась". Если надо писать - будем писать.

То что написанная вами программа думает, что оно "сохранилось" совершенно не означает, что оно сохранилось на самом деле. Это два разных события.

> > выгрузку в текстовик
> Принципиально это именно так делать? Я сейчас тупо в другом редакторе смотрю.

Нет, нормально, смотрите в другом, без проблем

**Comment by d-markevich** [comment]
> > Скорее не new а unsaved, ну или тогда прийдется вводить и new и unsaved. 
> Не вижу принципиальной разницы, в любом случае на сервере этих данных нет. New - в любом случае unsaved.

Да, unsaved покрывает new, но new не покрывает unsaved, а у вас было написано new. Т.е. в вашей формулировке отредактированные поля не выделялись бы, а значит был бы не понятен предмет валидации. Тут уже не вопрос цвета шрифта, а вопрос предмета валидации.

> Both у нас обе категории - Must-have и May-have. Попробую перефразировать, если так неясно.

Было не ясно.

 
> > Мы вроде bin не собирались редактировать?
> У нас записано, что собирались, но исключительно как hex.

> Там чуть выше пассажа про подкрашивание красным указано
> Обсудим с разработчиками, текущая имплементация предполагала in-place валидацию.

Пассаж не заметил, много очень букффф

Был не прав, делаем in-place



> > Предусловие...
> > Действие...
> > Реакция... 
> Вроде договаривались о том, что как раз такой формат с глубокой детализацией использовать не будем и будем писать высокоуровнево. Можно, конечно, и на детализированные тест-кейсы перейти, но это тогда будет вообще другой формат документа.

Вся жизнь это "предусловие-действие-реакция" но вы же не кончаете жизнь самоубийством из-за того, что она такая "детализированная". Когда я говорил "не нужна детализация" имел ввиду "поставить курсор в поле", "в меню выбрать пункт ХХХ потом пункт ХХХХ". Мы остаемся на уровне функций "что" (пользователь ввел новое значение), и пренебрегаем "как" (мышка, клава, пальцем). Не сказав в каком состоянии была система (предусловие), кака функция была запущена (редактирование, удаление, сохранение) и какая реакция (сохранил, вылетел, сгорел) невозможно описать систему. Вопрос не к детализации, вопрос в стиле - вы книгу пишите о путешествиях по миру а не алгоритм, вы описываете что система "может", а не как она себя ведет. Попробуйте более формально смотреть на вещи, я реально половину вашего текста не понял.

> Мы рассматриваем этот кусок функционала как один юз-кейс, с точки зрения Agile это одна Story. Соответственно, закрываем мы ее тоже одним куском, поэтому и чеклист такой. Согласитесь, не очень логично закрывать, например, редактирование без сохранения или сохранение без редактирования.

Согласен, но вы опять пишете глаголы без существительного, опять потерян контекст. Можно сначала закрыть (1) редактирование и сохранение существующих атрибутов, потом (2) создание, удаление атрибутов как таковых, (3) потом создание и удаление объектов.  Но в общем-то вам решать...

**Comment by dmitry-vrachev** [comment]
Я переписал всё в другом стиле, с учетом замечаний и изменений в имплементации: 
#14 
Этот issue закрываю как есть.
