### ISSUE TITLE
Test case: Complex search

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#16]
**Story description:**

LDAP search supports search using quite complex filters include several conditions with grouping.

**Use case: search LDAP records**

- Precondition: 
Application is started and connected to some LDAP server.

|User action:|System reaction:|
|---|---|
|User opens LDAP search dialog and sets base search DN, filter for searching attributes and attributes to display. User starts search.| The list of objects matching the filtering conditions is displayed. For each item only its DN and selected list of attributes are displayed. Only the objects from the sub-tree starting from base search DN are displayed in the search results.|
|User changes base search DN and starts search.|Search results are changed including only the objects from the sub-tree starting from new base search DN.|
|User changes filter conditions including logical and/or compare operations in RFC notation (like "(&(atttibute1=FOO)(attribute2=BAR))")|Search results are changed according to changes in filter conditions|
|User changes the attributes list and starts search.| Search results are changed including the attributes set by user.|

Note:
Supported logical operations are:
 - AND(&) 
 - OR(|)
 - NOT(!)
Supported compare operations are: 
 - EQUAL TO(=)
 - APPROXIMATELY EQUAL TO(~=) 
 - LEXICOGRAHICALLY LESS THEN OR EQUAL TO (<=)
 - LEXICOGRAHICALLY GREATER THEN OR EQUAL TO (>=)

**Comment by d-markevich** [comment]
Егор, рассмотри кейс и результаты, я в поиске ничего не понимаю

**Comment by dmitry-vrachev** [comment]
@Shcherbich Егор, посмотрите тест-кейс, пожалуйста.

**Comment by Shcherbich** [comment]
С action все ок и ожидаемые результаты правильные, закрываю issue.
