### ISSUE TITLE
Connection by user-set base DN

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#19]

**Comment by dmitry-vrachev** [comment]
@d-markevich на всякий случай хочу уточнить - на мелкие баги вроде этой тест-кейсы пишем/не пишем? Или я проверяю и сразу закрываю?

**Comment by d-markevich** [comment]
А где грань "мелкий"? :-)

Закрывайте без, просто меня добавляйте в задачу, я буду смотреть и если не нравится писать
