### ISSUE TITLE
TLS Connection

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#20]
* На машине выполняющей Клиента находится открытый ключ CA, которым подписан сертификат Samba, с помощью которого клиент проверяет достоверность сертификата Samba. Ключ хранится в доверенном хранилище OS.
* Проверку сертификата клиента не производим.
* Подключаемся по TLS с именем пользователя и паролем.

**Comment by d-markevich** [comment]
Сертификаты устанавливаются вместе с ПО и хранятся в операционной системе, все программы на данной машине используют сертификаты совместно.

---

Почему у нас в заголовке написано "Connect to server using SSL/TLS without password"? Мы не аутентифицируем даже simple? Полагаемся на сертификат?

---

@Shcherbich Что бы уже закончить эту тему. Если у нас все машины используют одинаковые сертификаты и мы используем оба сертификата, и сервера и клиента, то зачем нам CA? СА имеет смысл в том случае, если мы будем их отзывать, а для этого они должны быть индивидуальными хотя бы до уровня машины.

**Comment by d-markevich** [comment]
@andrew-tyapukhin Как говорилось в анекдоте - "концепция поменялась", см. ниже. Возможно стоит объединить эту задачу с #47 как "Подключение к серверу".
* На машине выполняющей Клиента находится открытый ключ Samba, с помощью которого клиент проверяет достоверность сертификата Samba. Ключ хранится в доверенном хранилище OS.
* Проверку сертификата клиента не производим.
* Подключаемся по TLS с именем пользователя и паролем.

**Comment by Shcherbich** [comment]
Маленькая корректировка:
* На машине выполняющей Клиента находится открытый ключ CA, которым подписан сертификат Samba, с помощью которого клиент проверяет достоверность сертификата Samba. Ключ хранится в доверенном хранилище OS.

**Comment by dmitry-vrachev** [comment]
![image](https://user-images.githubusercontent.com/46187174/53086479-408c4d00-3516-11e9-80a5-5f7542b83e73.png)
More specific error messages are expected.
