### ISSUE TITLE
View ObjectClasses

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#21]
When User see the Entry he can see list of Entry ObjectClasses and ObjectClass for each Atribute

**Comment by andrew-tyapukhin** [comment]
estimation 3sp

**Comment by dmitry-vrachev** [comment]
Currently there are several attributes where parent objectClass is set for the object, but is displayed as "???".
E.g. for users: countryCode.

**Comment by dmitry-vrachev** [comment]
Completed with the following limitation: in case some object has an attribute which does not belong to the objectClasses of this object - the class is displayed as '???'.
E.g: the user Administrator from test Samba AD has the set of objectClasses: top,person,organizationalPerson,user. It also has the attribute objectSid.
![image](https://user-images.githubusercontent.com/46187174/52634792-2bda0480-2ed9-11e9-9145-7f06e9311897.png)
The attribute objectSid does not belong to any of objectClasses of this object:
![image](https://user-images.githubusercontent.com/46187174/52634877-66dc3800-2ed9-11e9-9694-8affe65b1ba4.png)

So, the class for the attribute objectSid is displayed as ???.

@d-markevich @Shcherbich is this OK?

**Comment by d-markevich** [comment]
Я услышал, пока ничего не могу сказать, так на должно быть. Думаю

Dmitry

**Comment by d-markevich** [comment]
[objectSid](https://ldapwiki.com/wiki/ObjectSID) это атрибут Microsoft Active Directory.

Предлагаю пока считать это нормальным, если нам понадобятся какие-то поля AD у которых не будет класса, тогда будем разбираться.

окончательное решение @Shcherbich

**Comment by dmitry-vrachev** [comment]
@Shcherbich так это окончательный вердикт, закрываем задачу, или еще ждем финального решения?

**Comment by d-markevich** [comment]
Окончательное...

Это все поля AD, мы уже вылезли за рамки начальных целей - чистый LDAP, эти поля мы никогда не будем сами заполнять, их самба будет. В бизнелогике отрегулируем
