### ISSUE TITLE
Show ObjectClasses when adding/removing Attributes 

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#22]
When User create new Attribute he may first select ObjectClass, in this case list of available new Attributes contains only Attributes that belong to the selected ObjectClass

**Comment by d-markevich** [comment]
Если мы делаем окно добавления/удаление доп классов то в нем можем и показывать добавляемые/удаляемые атрибуты

**Comment by andrew-tyapukhin** [comment]
estimation 4sp

**Comment by dmitry-vrachev** [comment]
1. Select some user, open New Attribute dialog.
 Expected: common attributes like 'description' are shown for all available objectClasses.
 Actual: 'description' is shown for the objectClass 'top' only.
---
2. The values in the dropdowns look ugly, the text should be moved to right a bit.
---
3. The header of the dialog window should be 'New Attribute', not 'New Attribute Dialog'.

**Comment by andrew-tyapukhin** [comment]
2. The values in the dropdowns look ugly, the text should be moved to right a bit.
done
3. The header of the dialog window should be 'New Attribute', not 'New Attribute Dialog'.
done

**Comment by d-markevich** [comment]
Мы вроде когда последний (со мной) раз совещались решали эту функцию не реализовывать, если сделали пускай остается, но доводить по внешнему виду точно не надо.

Андрей, если ugly и заголовок это единственный замечания - закрывайте

**Comment by dmitry-vrachev** [comment]
4. Wrong type is displayed for attributes
![image](https://user-images.githubusercontent.com/46187174/52627508-9b92c400-2ec6-11e9-9df2-f2afb64896db.png)

**Comment by andrew-tyapukhin** [comment]
fixed 0.5.13

**Comment by dmitry-vrachev** [comment]
5. Attributes are not shown at all when adding new attribute to new entity

**Comment by dmitry-vrachev** [comment]
Complete testing is blocked by #42  - cannot check the case with objectClass removal.
