### ISSUE TITLE
Tooltip for ObjectClass

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#23]
User use tooltip to see ObjectClass description

**Comment by andrew-tyapukhin** [comment]
estimation 3sp

**Comment by andrew-tyapukhin** [comment]
SP = story point, оценка трудоемкости задачи (1sp принято за 4 часа)

**Comment by dmitry-vrachev** [comment]
@d-markevich вопрос: мы реализовали показ в тултипах description-ов из схемы, но в процессе тестирования выяснилось, что по крайней мере в схеме Самбы все description-ы как для аттрибутов, так и для классов пустые. Вы планируете в дальнейшем использовать какую-то кастомную схему с заполненными description-ами? Или мы можем попробовать добавить в тултип еще какую-то информацию.

**Comment by dmitry-vrachev** [comment]
@Shcherbich Егор, возможно, вы можете ответить на вопрос выше, пока Дмитрий занят.

**Comment by Shcherbich** [comment]
Мы планировали расширять схему самбы, добавляемые атрибуты мы будем сопровождать DESC.

**Comment by d-markevich** [comment]
> Или мы можем попробовать добавить в тултип еще какую-то информацию.

Нет, не надо

Для тестов надо их просто создать, справитесь или нам помочь?

**Comment by dmitry-vrachev** [comment]
> Для тестов надо их просто создать, справитесь или нам помочь?
Справимся и сами, но если вы можете быстро дать уже готовую расширенную схему и/или инструкции по ее обновлению - это, конечно, сэкономит время.

**Comment by d-markevich** [comment]
@Shcherbich Прошу добавить desription для проверки

**Comment by d-markevich** [comment]
Забили, нет на них времени
