### ISSUE TITLE
Tooltip for Attribute

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#24]
User use Tooltip to see Attribute description

**Comment by andrew-tyapukhin** [comment]
Is it correct that description tooltip will be shown on attribute column only?

**Comment by andrew-tyapukhin** [comment]
estimation 2sp

**Comment by vitali-kabiak** [comment]
VK tested on standart LDAP server, some attributes have description
But on given of SAMBA - we have not any description of attributes

So, please TEST it on some servers or change schema with LDIF

**Comment by dmitry-vrachev** [comment]
Тот же вопрос, что и в #23

**Comment by d-markevich** [comment]
@Shcherbich Прошу добавить Description в парочку атрибутов существующей схемы для проверки работы.

**Comment by d-markevich** [comment]
Забили, нет на них времени
