### ISSUE TITLE
Atomic Edit

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#25]
The user shall complete current editing step for Attribute/Entry before perform the next one, modification shall be verified.
--
Мутно... Отредактировали один атрибут, верифицировали, сохранили, теперь можем редактировать следующий. Добавили класс, проверили, сохранили, теперь делаем следующее изменение. Не накапливаем много изменений особенно при изменении классов.

**Comment by dmitry-vrachev** [comment]
@d-markevich исходя из того, что проговорили на встрече в пятницу - требуемая функциональность реализована, кнопка Save есть. Закрываем issue?

**Comment by d-markevich** [comment]
> Закрываем issue?

Да
