### ISSUE TITLE
Generalized Time formats support

### ISSUE THREAD

**Issue by andrew-tyapukhin** [Shcherbich/QLdapEditor#32]
supported formats:
yyyymmddhhmmss.ffffff (local time)
yyyymmddhhmmss.ffffffZ (Coordinated Universal Time)
yyyymmddhhmmss.ffffff-hhmm (Time zone west)
yyyymmddhhmmss.ffffff+hhmm (Time zone east)
The seconds (ss) and microseconds (ffffff) can be omitted and defaults to 0.

**Comment by dmitry-vrachev** [comment]
1. Editor for Generalized Time format in grid does not work.

**Comment by andrew-tyapukhin** [comment]
resolved 0.5.20
