### ISSUE TITLE
New entity should be immediately shown in DIT

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#35]
Expected: new entity is shown in DIT immediately after creation (before saving)
Actual: new entity is shown in DIT only after saving.

**Comment by dmitry-vrachev** [comment]
Проверить: если нет parental DN-> ошибка

**Comment by d-markevich** [comment]
> new entity is shown in DIT immediately after creation (before saving)

Так а если оно потом не сохранится, то что? Будем убирать из дерева? Может все таки открыли окно - выбрали - нажали Ок - если сохранилось то видим в дереве. Не настаиваю...

**Comment by dmitry-vrachev** [comment]
Имеется в виду момент, когда в диаложке мы уже всё выбрали и ОК уже нажали, но аттрибуты данными не заполнили и новый объект еще не сохранили. Сейчас в дереве в этот момент ничего не отображается, что нелогично.

**Comment by dmitry-vrachev** [comment]
Expected: the new object is shown in DIT in scope of view area, not somewhere below where the user has to scroll.

**Comment by andrew-tyapukhin** [comment]
solved

**Comment by dmitry-vrachev** [comment]
>solved
Not working in b12

**Comment by dmitry-vrachev** [comment]
Also there is a glitch when the added object is not saved.
![image](https://user-images.githubusercontent.com/46187174/52622647-66cd3f80-2ebb-11e9-8f74-b3f65d25abbd.png)

**Comment by andrew-tyapukhin** [comment]
resolved 0.5.13

**Comment by d-markevich** [comment]
> moved this from **Waiting for acceptance** to **Done** in [QLDAPEditor](/Shcherbich/QLdapEditor/projects/1#card-17414887)

Опять запутали, что такое Done? Если все сделано и проверено закрывайте issue через кнопку Close, Close это и есть Done.
