### ISSUE TITLE
The objects in DIT should be sorted in alphabetical order 

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#36]
Expected: the objects in DIT are be sorted in alphabetical order in scope of each branch.
Actual: the objects in DIT are not sorted

**Comment by dmitry-vrachev** [comment]
Expected: the sorting order is not case-sensitive, i.e. the order is Aa..Zz, not A..Za...z.

**Comment by andrew-tyapukhin** [comment]
solved
