### ISSUE TITLE
User should have a possibility not to fill values of some Must attributes when creating an entity

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#37]
As the analysis shown, in Samba schema there are some attributes which cannot be filled by user, like nTSecurityDescriptor. At the same time it seems that Samba itself ignores nTSecurityDescriptor, although it's set as Must.

Proposed and agreed solution is:
* preferred solution: add some possibility for user to explicitly select Must attributes which will be left empty at the moment of entity creation, e.g. add some checkboxes;

* in case further analysis will show that the preferred solution is not possible - add a possibility for user to left all Must attributes empty and show a warning message like "Some Must attributes are still empty, save? (yes/no)".

This solution is agreed with @Shcherbich.

**Comment by dmitry-vrachev** [comment]
1. Если для хотя бы одного из классов аттрибут Must, то он отображается в Must.
2. аттрибут objectCategory показываем заполненным и нередактируемым
3. добавляем галочку "игнорировать аттрибут", описание в тултип. При выставлении галочки поле ввода для value неактивно, значение пустое.
4. для nTSecurityDescriptor, objectCategory, instanceType галочку выставляем сразу - мы не ожидаем, что их будет заполнять юзер.

**Comment by dmitry-vrachev** [comment]
Баги по уже имплементированному:
1. Если для хотя бы одного из классов аттрибут Must, то он отображается в Must.
2. классы для аттрибутов должны отображаться сразу
3. May аттрибуты не показываем

**Comment by andrew-tyapukhin** [comment]
version 0.5.17
