### ISSUE TITLE
Add new entity: stabilization

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#41]
b13
1. Attributes are not shown at all when adding new attribute to new entity
2. Changing structural class in 'Add new entity' dialog clears the 'RDN' field.

**Comment by andrew-tyapukhin** [comment]
resolved 0.5.15

**Comment by dmitry-vrachev** [comment]
b15.
1. Not all structural objectClasses are shown. E.g. for the user only 'top' and 'user' are shown.
2. We should show filled objectClass attribute with the full list together with the Must attributes.

**Comment by dmitry-vrachev** [comment]
3. All Must attributes should be shown after object creation.
4. createTimeStamp, modifyTimeStamp, sunSchemaSubEntry are shown as Must. Expected - as May.
5. Save works only on 2nd time.
6. 3 errors about 'cannot delete the attribute <Name>' appear during save.

**Comment by andrew-tyapukhin** [comment]
resolved 0.5.23
