### ISSUE TITLE
Auxiliary objectClasses for existing entity cannot be changed

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#42]
Expected: auxiliary objectClasses for existing entity can be changed via 'Edit entry' dialog.
Also wrong structural class is displayed.
![image](https://user-images.githubusercontent.com/46187174/52634268-d6512800-2ed7-11e9-9fcd-bc8b913a976c.png)

**Comment by andrew-tyapukhin** [comment]
resolved 0.5.14

**Comment by dmitry-vrachev** [comment]
1. 
![image](https://user-images.githubusercontent.com/46187174/52714538-2baa3980-2fab-11e9-8e43-6098de93ba93.png)

As the structural objectClass can be only one, we should display the lowest child from objectClass as the structural class.
E.g. for the user account we should display 'user' as the structural object class.
Parent classes should not be displayed at all.

2. 
![image](https://user-images.githubusercontent.com/46187174/52714608-5a281480-2fab-11e9-9df8-0a5be73a22a1.png)
Auxiliary class is displayed as structural.

**Comment by d-markevich** [comment]
Не понял, зачем закрыли? Вроде передали в переделку и сразу закрыли... Если была переделка "in progress" то потом должен быть "review" а уже потом "close"

**Comment by dmitry-vrachev** [comment]
Я, похоже, кнопкой ошибся, спасибо.

**Comment by dmitry-vrachev** [comment]
checked on b24
1. @andrew-tyapukhin GUI: expected that when new objectClass is added, the value of objectClass in grid is changed and the change is marked with bold.
2. @vitali-kabiak create a user, save, add the mailRecipient auxiliary class. Expected - change can be saved, actual - the message "Server is unwilling to perform" rises and the application fails with the 50\50 probability.

**Comment by andrew-tyapukhin** [comment]
@1 fixed in version 0.5.26

**Comment by dmitry-vrachev** [comment]
#1 verified on b26

**Comment by dmitry-vrachev** [comment]
issue 2 checked with b31, nothing changed
