### ISSUE TITLE
Application shouldn't read full tree on connection

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#43]
Actual: full tree is read out on connection.
Expected: it shouldn't.

~Actual:
when establishing connection there is a significant delay between when connection dialog is closed and the main window is opened because some data is fetched in this moment.
Expected:
connection dialog is not closed until the application is ready to show main window OR this use case is solved in some other way.~

**Comment by andrew-tyapukhin** [comment]
resolved 0.5.16

**Comment by d-markevich** [comment]
Забыли это юзабилити 
Нам не надо
Чтение в начале всего дерева не типичная для будущей нормальной работы операция

Dmitry

**Comment by andrew-tyapukhin** [comment]
version 0.5.25
