### ISSUE TITLE
Add 'GroupOfNames'

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#46]
Заносим Entry в атрибут GroupOfNames, убедится, что у Entry появляется свойство MemberOf. Можно проверить на объектах схемы Horizont.

**Comment by d-markevich** [comment]
Немного разобрались

[GroupOfNames](https://ldapwiki.com/wiki/GroupOfNames) это атрибут LDAP.

[MemberOf](https://ldapwiki.com/wiki/MemberOf) это атрибут Active Directory, который она выставляет автоматически при включении Entry в GroupOfNames.

Поскольку мы все одно пользуемся Samba то не будем отрицать ее схему.

Наша задача - научиться заносить Entry в атрибут GroupOfNames, убедится, что у Entry появляется свойство MemberOf. Можно проверить на объектах схемы Horizont.

@Shcherbich

**Comment by dmitry-vrachev** [comment]
@d-markevich Samba и вообще AD использует не GroupOfNames, а [Group](https://ldapwiki.com/wiki/Group-AD). Нам поддержать оба варианта?

**Comment by d-markevich** [comment]
> Samba и вообще AD использует не GroupOfNames, а [Group](https://ldapwiki.com/wiki/Group-AD). Нам поддержать оба варианта?

На сценарий минимум - мы заносим Entry в GroupOfNames нашего собственного OB, в принципе этого достаточно, далее мы можем работать поиском.

Если Samba при этом еще автоматически добавить в Entry обратную ссылку MemberOf нам будет проще искать, не надо будет шарить по дереву. Но это удобная опция, но не обязательное поведение.

**Comment by andrew-tyapukhin** [comment]
version 0.5.30

**Comment by dmitry-vrachev** [comment]
1. Expected: menu item 'Manage users in group' is available in context menu for object in DIT.

**Comment by dmitry-vrachev** [comment]
2. Dialog window needs revising 
![image](https://user-images.githubusercontent.com/46187174/53343827-50df6600-3922-11e9-8179-482435fdc9b4.png)
