### ISSUE TITLE
Add support of selecting connection from different settings

### ISSUE THREAD

**Issue by andrew-tyapukhin** [Shcherbich/QLdapEditor#50]
Now we have only 1 connection settings.
Add ability for user to select connection from different settings

**Comment by andrew-tyapukhin** [comment]
version 0.5.35

**Comment by dmitry-vrachev** [comment]
1. Expected that connection names are displayed, not file names 
![image](https://user-images.githubusercontent.com/46187174/53337814-51243500-3913-11e9-969e-d2600f8b2048.png)
2. Expected that all labels are on same level.
3. Expected that on application start last used connection settings are auto-loaded.

**Comment by andrew-tyapukhin** [comment]
fix 0.5.41
