### ISSUE TITLE
Create VMWare Horizon User

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#53]
Admin create `User` in selected `Unit`, this User is recognised as User by `VMWare Horizon`.

Определить набор полей, которые обязательно должен заполнить admin, что бы User был опознан `VMWare Horizon`.

**Comment by d-markevich** [comment]
@andrew-tyapukhin @Shcherbich 

Новая функция, она уже In-House, т.е. для нашего приложение. Андрей, анализируйте, спрашивайте.

**Comment by andrew-tyapukhin** [comment]
какая информация по необходимым полям есть у вас?

**Comment by d-markevich** [comment]
> какая информация по необходимым полям есть у вас?

Ни какой :-) Надо пересаживаться на наш сервер, там уже развернут Horizon, смотреть из чего состоят существующие User, анализировать и пробовать. Можно попробовать поискать документацию. Мы анализом этого вопроса не занимались, как я и сказал на последней очной встрече - мы подошли к горизонту наших знаний, дальше исследуем совместно.

**Comment by dmitry-vrachev** [comment]
> Надо пересаживаться на наш сервер, там уже развернут Horizon, смотреть из чего состоят существующие User, анализировать и пробовать.

Тогда хотелось бы попасть еще в админку вашего Horizon, чтобы видеть, как там отображаются и распознаются созданные нами элементы. Можем, конечно, и у себя поднять, но продукт вообще незнакомый, займёт много времени.

**Comment by d-markevich** [comment]
> Тогда хотелось бы попасть еще в админку вашего Horizon

Для этого сервер и развернут, за подключением к @Shcherbich

**Comment by andrew-tyapukhin** [comment]
пользователь test99 создался  в QLdapEditor правильно (добавлен в группу VDIUser,  set password, enabled).
После добавления его как Desktop EntiElement в Horizon Console, можно зайти на виртуальную машину test-1 под этим пользователем


![image](https://user-images.githubusercontent.com/46192269/53621712-78774c80-3c08-11e9-9ac9-9e9412e40e6c.png)
