### ISSUE TITLE
Add User to existing Horizon Group

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#54]
- Admin assign existing User (`Horizon User`) to one or a number of existing `Roles`=`VMWare Horizon User Group`.
- The admin may withdraw assignment.
- The admin  may rename `Role` using application.
- When `Role` is deleted from the system all User assignments from this Role is also deleted.

**Note**: `Roles`=`VMWare Horizon User Group` are managed (add, delete, modify) using Horizon Manager. We need to check is it possible to rename group from back-door.

**Comment by d-markevich** [comment]
@andrew-tyapukhin Анализируйте, спрашивайте

@Shcherbich Проверь меня

**Comment by andrew-tyapukhin** [comment]
создал пользователя testUser-99 на dc02, добавил его в группу HorizonAdmins, сохранил
в общем это пока все что можно сделать с нашей стороны.
а теперь вопросы:
1. как мы можем убедиться что пользователь создан в WmMware Users?
2. как можно убедиться что пользователь имеет требуемы права?
3. как можно поменять пароль - нет такого поля (или оно не создано) ?

**Comment by d-markevich** [comment]
> Создал пользователя testUser-99 на dc02, добавил его в группу HorizonAdmins, сохранил
в общем это пока все что можно сделать с нашей стороны.

А вы посмотрели из чего состоят уже существующие user? У меня руки не дошли и дойдут только к выходным.

> как мы можем убедиться что пользователь создан в WmMware Users?
> как можно убедиться что пользователь имеет требуемы права?

Через приложение VMWare, оно там тоже есть на сервере.

> как можно поменять пароль - нет такого поля (или оно не создано) ?

Не знаю, вообщем вопрос на нашей стороне. Завтра попробуем разобраться и сообщить.

**Comment by andrew-tyapukhin** [comment]
according https://docs.vmware.com/en/VMware-Horizon-7/7.5/horizon-console-administration/GUID-D2ADFD46-9375-4B6D-96D9-58E8133E5D59.html
we need access to Horizon Connection Server for login to Horizon Console

**Comment by andrew-tyapukhin** [comment]
доступ к  Horizon Console предоставлен

**Comment by dmitry-vrachev** [comment]
Bug on b53: application closes on adding user to group

**Comment by andrew-tyapukhin** [comment]
fixed  0.5.54
