### ISSUE TITLE
Add to Group - stabilization

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#56]

**Comment by dmitry-vrachev** [comment]
1. objectClass should be displayed as Must 
![image](https://user-images.githubusercontent.com/46187174/53243307-7a955480-36b8-11e9-99fc-d651fc48bf55.png)

**Comment by d-markevich** [comment]
Можно предложение? Раз уж мы мучаемся с ActiveDirectory и признали тот факт, что какие поля заполняются самой самой Sambой может вы введем понятие "списк обязательных полей заполняемых сервером AD" и будем с точки зрения приложения считать такие поля необязательным для пользователя. По мере накопления опыта будем этот список расширять.

**Comment by dmitry-vrachev** [comment]
> Можно предложение? Раз уж мы мучаемся с ActiveDirectory и признали тот факт, что какие поля заполняются самой самой Sambой может вы введем понятие "списк обязательных полей заполняемых сервером AD" и будем с точки зрения приложения считать такие поля необязательным для пользователя. По мере накопления опыта будем этот список расширять.

Мы по сути это уже сделали, три галочки Ignore на скриншоте выставляются эдитором автоматически. Пока больше не видно, чем расширить список.

**Comment by d-markevich** [comment]
> три галочки Ignore на скриншоте выставляются эдитором автоматически.

Согласен

**Comment by dmitry-vrachev** [comment]
Bug 1. is validated on b38, issue closed until new related bugs.

**Comment by dmitry-vrachev** [comment]
2. New group member should be displayed as bold.

**Comment by andrew-tyapukhin** [comment]
new group memeber aalready shown as bold, but in gray color - so may be it makes it looked wrong
![image](https://user-images.githubusercontent.com/46192269/53573800-57b6e480-3b7f-11e9-9927-de801c023a8a.png)

**Comment by dmitry-vrachev** [comment]
Well we should made this bold more bold, or revise all color scheme.

**Comment by andrew-tyapukhin** [comment]
![image](https://user-images.githubusercontent.com/46192269/53630888-3a872200-3c22-11e9-97bd-c1e6e6e880aa.png)
version 0.5.49

**Comment by dmitry-vrachev** [comment]
Yellow string background looks OK, closed.
