### ISSUE TITLE
User is not warned about losing attributes when removing auxiliary objectClass

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#57]

**Comment by dmitry-vrachev** [comment]
Expected: when user removes some auxiliary objectClasses they see a list of attributes that will be deleted after removing these classes.

**Comment by andrew-tyapukhin** [comment]
![image](https://user-images.githubusercontent.com/46192269/53498631-bc0e7100-3ab7-11e9-8e41-28d5f28de812.png)

**Comment by andrew-tyapukhin** [comment]
fix 0.5.43
