### ISSUE TITLE
Research differences in QT elements look on different machines

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#58]
1. Adjust controls in New entry dialog
![image](https://user-images.githubusercontent.com/46187174/53486878-09c8b080-3a9b-11e9-82e9-3daca9ea46b0.png)

**Comment by dmitry-vrachev** [comment]
2. RDN is cleared when Structural class is changed.

**Comment by andrew-tyapukhin** [comment]
fix 0.5.42

**Comment by dmitry-vrachev** [comment]
Checked in b45. More controls adjusting needed

**Comment by andrew-tyapukhin** [comment]
version 0.5.47

**Comment by dmitry-vrachev** [comment]
Checked in 0.5.51, no changes on my machines. @andrew-tyapukhin we need to research why application looks different on your machine.

**Comment by dmitry-vrachev** [comment]
Rename issue from "New entry dialog - stabilization" to "Research differences in QT elements look on different machines"

**Comment by andrew-tyapukhin** [comment]
version 0.5.52
