### ISSUE TITLE
Add a possibility to enable/disable AD users and add some GUI display for this.

### ISSUE THREAD

**Issue by dmitry-vrachev** [Shcherbich/QLdapEditor#59]

**Comment by dmitry-vrachev** [comment]
1. Graying user name for disabled users does not look good, let's try to change icon instead as it's done in MS AD console.
![image](https://user-images.githubusercontent.com/46187174/53565853-a6f31a00-3b6b-11e9-9ebc-cae74ed6914a.png)

**Comment by andrew-tyapukhin** [comment]
version 0.5.47: add new icon for disabled user in DIT
